---
title: "gentrym1-OriginalHomeworkCode_02"
author: "Gentry Miller"
format: html
editor: visual
theme: cayman
---

# Titis in the Mist

## Prelim

```{r}
install.packages(c("prettydoc", "manipulate"))
library(prettydoc)
library(manipulate)
```

## Poisson Distribution

For the Poisson Distribution, the PMF is

$$ f(x) = \frac{\lambda^x e^{-\lambda}}{x!} $$

Where x = {0, 1, 2, ...} and $\mu_X = \lambda$ and $\sigma^2_X = \lambda$

```{r}
# What is the probability she will hear more than 8 calls during any given session?

a1 <- ppois(8, 15, lower.tail=FALSE)
print(paste0("The probability of observing more than 8 calls is ", a1))

# What is the probability that she will observe 0 calls?

a2 <- ppois(0, 15, lower.tail=TRUE)
print(paste0("The probability of observing exactly 0 calls is ", a2))

# What is the probability that she will hear exactly 3 calls?

a3 <- ppois(3, 15, lower.tail=TRUE)
print(paste0("The probability of observing exactly 3 calls is ", a3))
```

```{r}
# Plot the relevant Poisson Distribution
x <- 0:30 # range of values for x
l = 15 # mean (lambda)
probset <- dpois(x = x, lambda = l)
barplot(probset, names.arg = x, space = 0, xlab = "x", ylab = "Pr(X = x)", main = "Probability Mass Function", col="lightblue")
```

```{r}
# Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).

d <- rpois(n=104, lambda=15)
hist(d, xlim=c(0, 30), xlab="x", ylab="Frequency", main="Distribution of Simulated Observations", col="bisque2")

# How does your histogram compare to the shape of the PMF you plotted above?

# The simulated observations follow the general shape of the PMF. When I increased n from 104 to 10^4, the shape was even more similar because as n increases the histogram will converge on the PMF (where n = infinity)
```
