---
title: "gentrym1-OriginalHomeworkCode_02"
author: "Gentry Miller"
format: html
editor: visual
theme: cayman
---

# Titis in the Mist

## Prelim

```{r}
install.packages(c("prettydoc", "manipulate"))
library(prettydoc)
library(manipulate)
```

#Carly's comment: Don't forget to put the table of content that Chris asked for.

#Carly's comment: Don't forget to make each question fall under the Header 2 title.

#Carly's comment: Don't forget to add the picture that he asks for as well!

## Poisson Distribution

For the Poisson Distribution, the PMF is

$$ f(x) = \frac{\lambda^x e^{-\lambda}}{x!} $$

Where x = {0, 1, 2, ...} and $\mu_X = \lambda$ and $\sigma^2_X = \lambda$

```{r}
#| label: Questions 1-3

# 1. What is the probability she will hear more than 8 calls during any given session?

a1 <- ppois(8, 15, lower.tail=FALSE)
print(paste0("The probability of observing more than 8 calls is ", a1))

# 2. What is the probability that she will observe 0 calls?

a2 <- ppois(0, 15, lower.tail=TRUE)
print(paste0("The probability of observing exactly 0 calls is ", a2))

# 3. What is the probability that she will hear exactly 3 calls?

a3 <- ppois(3, 15, lower.tail=TRUE)
print(paste0("The probability of observing exactly 3 calls is ", a3))
```

```{r}
#| label: Question 4

# 4. Plot the relevant Poisson Distribution

x <- 0:30 # range of values for x
l = 15 # mean (lambda)
probset <- dpois(x = x, lambda = l)
barplot(probset, names.arg = x, space = 0, xlab = "x", ylab = "Pr(X = x)", main = "Probability Mass Function", col="lightblue")

#Carly's comment: I ran my code similarly to this one, but got different results for some reason. I have a feeling yours might be correct, but I will double check mine just in case. I love how yours is organized and it's easily understandable. I will consider this next time I create my plots. Amazing work!!!
```

```{r}
#| label: Questions 5 & 6

# 5. Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).

d <- rpois(n=104, lambda=15)

# 6.1 Plot the simulated results using hist() and use xlim() to set the horizontal limits to be from 0 to 30.

hist(d, xlim=c(0, 30), xlab="x", ylab="Frequency", main="Distribution of Simulated Observations", col="bisque2")

# 6.2 How does your histogram compare to the shape of the PMF you plotted above?

print("The simulated observations follow the general shape of the PMF. When I increased n from 104 to 10^4, the shape was even more similar because as n increases the histogram will converge on the PMF (where n = infinity)")

#Carly's comment: I love how your histogram looks here! I have a feeling I ran mine very differently (mainly because the code for this was confusing to figure out). I'm not so sure if mine was correct by looking at how yours looks like. I will definitely take into consideration adding color to my plots just the way you did it. It looks more appealing and it's easy to understand, too. Great work!!!
```
